### ISSUE TITLE
When will a release be made?

### ISSUE THREAD

**Issue by Zero3K** [Alex313031/chromium-xp#1]
*subject*

**Comment by Alex313031** [comment]
@Zero3K Soon. I've been working out some bugs building with visual studio 2015 instead of 2013.

**Comment by Zero3K** [comment]
Thanks. I will test it under ReactOS.

**Comment by Alex313031** [comment]
@Zero3K Here you go > https://github.com/Alex313031/chromium-xp/releases/tag/M49.0.2623.113

**Comment by Zero3K** [comment]
I tested it under a ReactOS VM. It isn't working as intended (The pages are crashing and its UI is messed up). Please make a bug report on its JIRA, which is located at https://jira.reactos.org/secure/Dashboard.jspa. You can make an account for it at https://reactos.org/roslogin/?p=register.

**Comment by Alex313031** [comment]
@Zero3K To make sure it isn't just that Chromium wont run on it, can you try this vanilla release > https://chromium.woolyss.com/f/chromium_win32_49.0.2623.112_r403382_sync.exe

**Comment by Zero3K** [comment]
The same issue still happens. Maybe a SSE2 version will work better.

**Comment by Alex313031** [comment]
@Zero3K Your wish is my command lol: https://github.com/Alex313031/chromium-xp/releases/tag/M49.0.2623.113-2

**Comment by Zero3K** [comment]
Oh, it is an already known bug that has a fix which hasn't been made in to a PR as of now.
