### ISSUE TITLE
Sse2

### ISSUE THREAD

**Issue by vertaa** [Alex313031/chromium-xp#3]
I still have an old Pentium 4 around, so having this browser support sse2 would totally make it more awesome. I'm remembering when they just started making dual core available. When they stop having two cpus on tyan motherboards. Sad day.

**Comment by Alex313031** [comment]
@vertaa I got a Pentium 4 with hyperthreading as well.

Performance benchmarks between SSE2 and SSE3 builds show no difference, and the size is almost the same, so builds from now on will just be SSE2. I'll update you here when next release comes out.

**Comment by Alex313031** [comment]
@vertaa Here you go, sir > https://github.com/Alex313031/chromium-xp/releases/tag/M49.0.2623.113-2

**Comment by vertaa** [comment]
@Alex313031 thank you.
